
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 24 20:35:24 CST 2020
//----------------------------------------------------

package AnalizadorColors;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Rojo = 7;
  public static final int Azul = 8;
  public static final int coma = 6;
  public static final int cierraLlaves = 3;
  public static final int Id = 14;
  public static final int Hex = 10;
  public static final int Error = 15;
  public static final int Letter = 11;
  public static final int EOF = 0;
  public static final int abreLlaves = 2;
  public static final int error = 1;
  public static final int Verde = 9;
  public static final int Colores = 5;
  public static final int Numero = 13;
  public static final int Double = 12;
  public static final int dosPuntos = 4;
}

