
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 14 22:32:25 CST 2020
//----------------------------------------------------

package AnalizadorPnt;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 31;
  public static final int cierraLlaves = 27;
  public static final int OperadorLogico = 22;
  public static final int dobleEquals = 34;
  public static final int Mul = 14;
  public static final int coma = 10;
  public static final int Res = 13;
  public static final int COM = 24;
  public static final int Int = 5;
  public static final int Inst = 29;
  public static final int Double = 19;
  public static final int Sum = 12;
  public static final int equals = 11;
  public static final int abreParen = 17;
  public static final int abreCor = 3;
  public static final int Operador = 21;
  public static final int Cadena = 20;
  public static final int EOF = 0;
  public static final int Num = 16;
  public static final int pintar = 33;
  public static final int If = 30;
  public static final int abreLlaves = 26;
  public static final int Bool = 23;
  public static final int error = 1;
  public static final int cierraCor = 4;
  public static final int Id = 6;
  public static final int Punto = 28;
  public static final int Vars = 2;
  public static final int Div = 15;
  public static final int While = 32;
  public static final int puntoComa = 9;
  public static final int String = 7;
  public static final int cierraParen = 18;
  public static final int Error = 25;
  public static final int Boolean = 8;
}

