
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 08 22:52:15 CST 2020
//----------------------------------------------------

package AnalizadorLienzos;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cierraLlaves = 3;
  public static final int Verde = 12;
  public static final int Numero = 18;
  public static final int Fond = 8;
  public static final int type = 7;
  public static final int coma = 9;
  public static final int ERROR = 22;
  public static final int COM = 25;
  public static final int Rojo = 11;
  public static final int Double = 19;
  public static final int Cadena = 21;
  public static final int EOF = 0;
  public static final int Hex = 23;
  public static final int Azul = 13;
  public static final int Id = 20;
  public static final int error = 1;
  public static final int abreLlaves = 2;
  public static final int Size = 10;
  public static final int Image = 17;
  public static final int Letter = 24;
  public static final int dosPuntos = 4;
  public static final int Posy = 16;
  public static final int Posx = 15;
  public static final int Cuadro = 14;
  public static final int Lienzos = 5;
  public static final int Nombre = 6;
}

