/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drawgif;

import Interfaz.EditorDeTexto;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhonny
 */
public class panelError extends javax.swing.JPanel {

    /**
     * Creates new form panelError
     */
    public panelError() {
        initComponents();
        
    }

    public void init(ArrayList<Errors> errors) {
        DefaultTableModel t = new DefaultTableModel();
        String array[] = {"Dato", "Linea","Columna"};
        for (String array1 : array) {
            t.addColumn(array1);
        }
        this.jTable1.setModel(t);
        for (int i = 0; i < errors.size(); i++) {
            String string[]={errors.get(i).dato,String.valueOf(errors.get(i).fila),String.valueOf(errors.get(i).columna)};
            t.addRow(string);
        }
        
        this.jTable1.setModel(t);
    }
     public void init2(ArrayList<Errors> errors) {
        DefaultTableModel t = new DefaultTableModel();
        String array[] = {"Dato", "Linea","Columna","info"};
        for (String array1 : array) {
            t.addColumn(array1);
        }
        this.jTable1.setModel(t);
        for (int i = 0; i < errors.size(); i++) {
            String string[]={errors.get(i).dato,String.valueOf(errors.get(i).fila),String.valueOf(errors.get(i).columna),errors.get(i).solucion};
            t.addRow(string);
        }
        
        this.jTable1.setModel(t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                        EditorDeTexto.Panel.remove(EditorDeTexto.Panel.getSelectedIndex());

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
