
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 08 17:47:36 CST 2020
//----------------------------------------------------

package AnalizadorTime;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cierraLlaves = 3;
  public static final int Numero = 8;
  public static final int coma = 14;
  public static final int Iden = 17;
  public static final int COM = 18;
  public static final int Start = 6;
  public static final int End = 7;
  public static final int Duracion = 15;
  public static final int abreCor = 12;
  public static final int Com = 11;
  public static final int Time = 5;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int cierraCor = 13;
  public static final int abreLlaves = 2;
  public static final int Id = 9;
  public static final int Image = 16;
  public static final int dosPuntos = 4;
  public static final int Error = 10;
}

